// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accent color configuration.
 */
export type AccentColor = {
  /**
   * Preset color name: "blue", "purple", "green", "orange", "pink", "red", "teal"
   */
  preset: string | null;
  /**
   * Custom hue value (0-360) for custom colors
   */
  customHue: number | null;
};
