// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error info for a single file that failed during bulk install.
 */
export type BulkInstallError = { filePath: string; fileName: string; message: string };
