// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkInstallError } from "./BulkInstallError";
import type { InstalledMod } from "./InstalledMod";

/**
 * Result of a bulk mod install operation.
 */
export type BulkInstallResult = { installed: Array<InstalledMod>; failed: Array<BulkInstallError> };
