// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for creating a new project.
 */
export type CreateProjectArgs = {
  name: string;
  displayName: string;
  description: string;
  authors: Array<string>;
};
