// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a discovered cslol-manager mod, shown in the UI selection step.
 */
export type CslolModInfo = {
  folderName: string;
  name: string;
  author: string;
  version: string;
  description: string;
};
