// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed representation of a `ltk://install` deep-link URL.
 */
export type DeepLinkInstallRequest = {
  url: string;
  name: string | null;
  author: string | null;
  source: string | null;
};
