// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error codes that can be communicated across the IPC boundary.
 * These are serialized as SCREAMING_SNAKE_CASE for TypeScript consumption.
 */
export type ErrorCode =
  | "IO"
  | "SERIALIZATION"
  | "MODPKG"
  | "LEAGUE_NOT_FOUND"
  | "INVALID_PATH"
  | "MOD_NOT_FOUND"
  | "VALIDATION_FAILED"
  | "INTERNAL_STATE"
  | "MUTEX_LOCK_FAILED"
  | "UNKNOWN"
  | "WORKSHOP_NOT_CONFIGURED"
  | "PROJECT_NOT_FOUND"
  | "PROJECT_ALREADY_EXISTS"
  | "PACK_FAILED"
  | "FANTOME"
  | "WAD"
  | "PATCHER_RUNNING"
  | "ZIP";
