// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata peeked from a .fantome archive without extracting content.
 */
export type FantomePeekResult = {
  name: string;
  author: string;
  version: string;
  description: string;
  wadFiles: Array<string>;
  suggestedName: string;
};
