// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event emitted during git repo import.
 */
export type GitImportProgress = { stage: string; message: string | null };
