// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The action a global hotkey triggers when pressed.
 */
export type HotkeyAction = "reloadMods" | "killLeague";
