// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for importing a project from a GitHub repository.
 */
export type ImportGitRepoArgs = { url: string; branch?: string };
