// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for importing a .fantome archive.
 */
export type ImportFantomeArgs = { filePath: string; name: string; displayName: string };
