// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModLayer } from "./ModLayer";

/**
 * A mod entry shown in the UI Library.
 */
export type InstalledMod = {
  id: string;
  name: string;
  displayName: string;
  version: string;
  description: string | null;
  authors: Array<string>;
  enabled: boolean;
  installedAt: string;
  layers: Array<ModLayer>;
  tags: Array<string>;
  champions: Array<string>;
  maps: Array<string>;
  /**
   * Directory where the mod is installed
   */
  modDir: string;
};
