// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event emitted per-file during bulk mod install.
 */
export type InstallProgress = { current: number; total: number; currentFile: string };
