// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayerInfo = {
  name: string;
  priority: number;
  description: string | null;
  fileCount: bigint;
};
