// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationPhase } from "./MigrationPhase";

/**
 * Progress event emitted during cslol migration (both packaging and installing phases).
 */
export type MigrationProgress = {
  phase: MigrationPhase;
  current: number;
  total: number;
  currentFile: string;
};
