// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mod layer shown in the UI.
 */
export type ModLayer = { name: string; priority: number; enabled: boolean };
