// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerInfo } from "./LayerInfo";

/**
 * Information returned by `inspect_modpkg`.
 */
export type ModpkgInfo = {
  name: string;
  displayName: string;
  version: string;
  description: string | null;
  authors: Array<string>;
  layers: Array<LayerInfo>;
  fileCount: bigint;
  totalSize: bigint;
};
