// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackFormat } from "./PackFormat";

/**
 * Arguments for packing a project.
 */
export type PackProjectArgs = { projectPath: string; outputDir?: string; format: PackFormat };
