// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a successful pack operation.
 */
export type PackResult = { outputPath: string; fileName: string; format: string };
