// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current phase of the patcher lifecycle.
 */
export type PatcherPhase = "idle" | "building" | "patching";
