// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatcherPhase } from "./PatcherPhase";

/**
 * Current status of the patcher.
 */
export type PatcherStatus = {
  /**
   * Whether the patcher is currently running.
   */
  running: boolean;
  /**
   * The config path the patcher was started with.
   */
  configPath: string | null;
  /**
   * Current phase of the patcher lifecycle.
   */
  phase: PatcherPhase;
};
