// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for starting the patcher.
 */
export type PatcherConfig = {
  /**
   * Optional log file path.
   */
  logFile?: string;
  /**
   * Timeout in milliseconds for hook initialization. Defaults to 5 minutes.
   */
  timeoutMs?: number;
  /**
   * Optional legacy patcher flags (matches `cslol_set_flags`).
   *
   * If not provided, defaults to 0 (equivalent to `--opts:none` in cslol-tools).
   */
  flags?: number;
};
