// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slugified profile name used as the filesystem directory name.
 */
export type ProfileSlug = string;
