// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileSlug } from "./ProfileSlug";

/**
 * A mod profile for organizing different mod configurations.
 */
export type Profile = {
  /**
   * Unique identifier (UUID)
   */
  id: string;
  /**
   * User-friendly name
   */
  name: string;
  /**
   * Slugified name used as the filesystem directory name
   */
  slug: ProfileSlug;
  /**
   * List of mod IDs enabled in this profile (maintains overlay priority order)
   */
  enabledMods: Array<string>;
  /**
   * Display order of all mods (enabled and disabled) in the UI
   */
  modOrder: Array<string>;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * Last time this profile was used/switched to
   */
  lastUsed: string;
};
