// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress payload emitted during protocol install download.
 */
export type ProtocolInstallProgress = {
  stage: string;
  bytesDownloaded: bigint;
  totalBytes: bigint | null;
  error: string | null;
};
