// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkshopAuthor } from "./WorkshopAuthor";

/**
 * Arguments for saving project configuration changes.
 */
export type SaveProjectConfigArgs = {
  projectPath: string;
  displayName: string;
  version: string;
  description: string;
  authors: Array<WorkshopAuthor>;
  tags: Array<string>;
  champions: Array<string>;
  maps: Array<string>;
};
