// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColor } from "./AccentColor";
import type { AuthorProfile } from "./AuthorProfile";
import type { Theme } from "./Theme";

export type Settings = {
  leaguePath: string | null;
  modStoragePath: string | null;
  /**
   * Directory where mod projects are stored (for Creator Workshop).
   */
  workshopPath: string | null;
  firstRunComplete: boolean;
  /**
   * Application theme (system, dark, or light).
   */
  theme: Theme;
  /**
   * Accent color configuration.
   */
  accentColor: AccentColor;
  /**
   * Optional backdrop image path for glassmorphism effect.
   */
  backdropImage: string | null;
  /**
   * Backdrop blur amount in pixels (default: 40).
   */
  backdropBlur: number | null;
  /**
   * Library view mode ("grid" or "list"). Defaults to "grid".
   */
  libraryViewMode: string | null;
  /**
   * Whether to patch TFT game files (Map22.wad.client). Default: false.
   */
  patchTft: boolean;
  /**
   * Whether to minimize to system tray instead of taskbar. Default: true.
   */
  minimizeToTray: boolean;
  /**
   * Whether to start the application minimized to the system tray. Default: false.
   */
  startInTray: boolean;
  /**
   * Whether the user has dismissed the cslol-manager migration banner.
   */
  migrationDismissed: boolean;
  /**
   * Global hotkey accelerator for reloading mods (e.g. "Ctrl+Shift+R").
   */
  reloadModsHotkey: string | null;
  /**
   * Global hotkey accelerator for killing League (e.g. "Ctrl+Shift+K").
   */
  killLeagueHotkey: string | null;
  /**
   * Whether the kill-league hotkey should also stop the patcher. Default: true.
   */
  killLeagueStopsPatcher: boolean;
  /**
   * Trusted domains for protocol installs. Downloads are only allowed from these domains.
   */
  trustedDomains: Array<string>;
  /**
   * Whether the library file watcher is enabled. Default: false.
   */
  watcherEnabled: boolean;
  /**
   * Whether to block mods from patching Scripts.wad.client. Default: true.
   */
  blockScriptsWad: boolean;
  /**
   * Additional WAD files to exclude from overlay building.
   */
  wadBlocklist: Array<string>;
  /**
   * Saved author profiles for the Creator Workshop.
   */
  authorProfiles: Array<AuthorProfile>;
  /**
   * ID of the default author profile auto-selected for new projects.
   */
  defaultAuthorProfileId: string | null;
};
