// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColor } from "./AccentColor";
import type { Theme } from "./Theme";

export type Settings = {
  leaguePath: string | null;
  modStoragePath: string | null;
  /**
   * Directory where mod projects are stored (for Creator Workshop).
   */
  workshopPath: string | null;
  firstRunComplete: boolean;
  /**
   * Application theme (system, dark, or light).
   */
  theme: Theme;
  /**
   * Accent color configuration.
   */
  accentColor: AccentColor;
  /**
   * Optional backdrop image path for glassmorphism effect.
   */
  backdropImage: string | null;
  /**
   * Backdrop blur amount in pixels (default: 40).
   */
  backdropBlur: number | null;
  /**
   * Library view mode ("grid" or "list"). Defaults to "grid".
   */
  libraryViewMode: string | null;
  /**
   * Whether to patch TFT game files (Map22.wad.client). Default: false.
   */
  patchTft: boolean;
  /**
   * Whether the user has dismissed the cslol-manager migration banner.
   */
  migrationDismissed: boolean;
};
