// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation result for a project.
 */
export type ValidationResult = { valid: boolean; errors: Array<string>; warnings: Array<string> };
