// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkshopLayer = {
  name: string;
  priority: number;
  description: string | null;
  stringOverrides: { [key in string]: { [key in string]: string } };
};
